"""ATLAS wire protocol."""

from atlas_shared.protocol.envelope import (
    PROTOCOL_VERSION,
    Envelope,
    format_timestamp,
    sign_envelope,
    signing_input,
    verify_envelope,
)
from atlas_shared.protocol.errors import AtlasProtocolError, ErrorCode
from atlas_shared.protocol.messages import (
    ActivityBatch,
    ActivitySample,
    AgentHello,
    ClientHello,
    ConnPing,
    ConnPong,
    DiskUsage,
    EnterSafeMode,
    ErrorPayload,
    HelloAck,
    MessageSpec,
    ModeChanged,
    ParsedMessage,
    SystemTelemetry,
    ToolCancel,
    ToolExecute,
    ToolFailure,
    ToolResult,
    build_envelope,
    known_types,
    parse_message,
    register,
    require_signature,
    spec_for,
)

__all__ = [
    "PROTOCOL_VERSION",
    "ActivityBatch",
    "ActivitySample",
    "AgentHello",
    "AtlasProtocolError",
    "ClientHello",
    "ConnPing",
    "ConnPong",
    "DiskUsage",
    "EnterSafeMode",
    "Envelope",
    "ErrorCode",
    "ErrorPayload",
    "HelloAck",
    "MessageSpec",
    "ModeChanged",
    "ParsedMessage",
    "SystemTelemetry",
    "ToolCancel",
    "ToolExecute",
    "ToolFailure",
    "ToolResult",
    "build_envelope",
    "format_timestamp",
    "known_types",
    "parse_message",
    "register",
    "require_signature",
    "sign_envelope",
    "signing_input",
    "spec_for",
    "verify_envelope",
]
